.TH hello 1
.de BP
.sp
.ti \-.2i
\(**
..

.SH NAME
hello \(em\& hello -- the greeting program

.SH SYNOPSIS
hello [-htvm] 
      [--help] 
      [--traditional] 
      [--version] 
      [--mail]

.SH DESCRIPTION
This documentation is no longer being maintained and may be inaccurate
or incomplete.  The Texinfo documentation is now the authoritative
source.

The GNU 
.I hello
program produces a familiar, friendly greeting.  It
allows nonprogrammers to use a classic computer science tool which
would otherwise be unavailable to them.  Because it is protected by the
GNU General Public License, users are free to share and change it.

.SH OPTIONS
.I hello
accepts the following options:

.TP
.B \-h --help
Print an informative help message describing the options and then exit.

.TP
.B \-v --version
Print the version number of
.I hello
on the standard error output and then exit.

.TP
.B \-t --traditional
Use the traditional greeting message `hello, world' rather than the 
more modern `Hello, world!'.

.TP
.B \-m --mail
Print your mail on the standard output.

.SH "AUTHORS"
GNU 
.I hello
was written by Mike Haertel, David MacKenzie,
Jan Brittenson, Charles Hannum, Roland McGrath, Noah Friedman, and
The King.  This man page was written by E. Larry Lidz

.SH "SEE ALSO"
.I The C Programming Language
by B. W. Kernighan and D. M. Ritchie, Prentice-Hall, New Jersey, 1978.
